src/Entity/Lead.php
<?php

namespace App\Entity;

use App\Repository\LeadRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=LeadRepository::class)
 * @ORM\Table(name="`lead`")
 */
class Lead
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $company;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $domain;

    /**
     * @ORM\Column(type="boolean")
     */
    private $conversion_status;

    /**
     * @ORM\Column(type="boolean")
     */
    private $broadcast_status;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="leads")
     * @ORM\JoinColumn(nullable=false)
     */
    private $created_by;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getCompany(): ?string
    {
        return $this->company;
    }

    public function setCompany(string $company): self
    {
        $this->company = $company;

        return $this;
    }

    public function getDomain(): ?string
    {
        return $this->domain;
    }

    public function setDomain(string $domain): self
    {
        $this->domain = $domain;

        return $this;
    }

    public function getConversionStatus(): ?bool
    {
        return $this->conversion_status;
    }

    public function setConversionStatus(bool $conversion_status): self
    {
        $this->conversion_status = $conversion_status;

        return $this;
    }

    public function getBroadcastStatus(): ?bool
    {
        return $this->broadcast_status;
    }

    public function setBroadcastStatus(bool $broadcast_status): self
    {
        $this->broadcast_status = $broadcast_status;

        return $this;
    }

    public function getCreatedBy(): ?User
    {
        return $this->created_by;
    }

    public function setCreatedBy(?User $created_by): self
    {
        $this->created_by = $created_by;

        return $this;
    }
}

src/Form/LeadType.php
<?php

namespace App\Form;

use App\Entity\Lead;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class LeadType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', TextType::class, [
                'label' => 'Lead Name',
                'attr' => ['class' => 'form-control'],
            ])
            ->add('company', TextType::class, [
                'label' => 'Company Name',
                'attr' => ['class' => 'form-control'],
            ])
            ->add('domain', TextType::class, [
                'label' => 'Domain',
                'attr' => ['class' => 'form-control'],
            ])
            ->add('conversion_status', CheckboxType::class, [
                'label' => 'Conversion Status',
                'attr' => ['class' => 'form-control'],
                'required' => false
            ])
            ->add('broadcast_status', CheckboxType::class, [
                'label' => 'Broadcast Status',
                'attr' => ['class' => 'form-control'],
                'required' => false
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Lead::class,
        ]);
    }
}

src/Controller/LeadController.php
<?php

namespace App\Controller;

use App\Entity\Lead;
use App\Form\LeadType;
use App\Repository\LeadRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/lead")
 */
class LeadController extends AbstractController
{
    /**
     * @Route("/", name="lead_index", methods={"GET"})
     */
    public function index(LeadRepository $leadRepository)
    { 
        // print_r($this->getUser()->getId());
        // exit;
        //  print_r($leadRepository->findByExampleField($this->getUser()->getId()));
        //  exit;
        return $this->render('lead/index.html.twig', [
            'leads' => $leadRepository->findLeadsWithBroadCasts($this->getUser()->getId()),
        ]);
    }

    /**
     * @Route("/new", name="lead_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $lead = new Lead();
        $form = $this->createForm(LeadType::class, $lead);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $lead->setCreatedBy($this->getUser());
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($lead);
            $entityManager->flush();

            return $this->redirectToRoute('lead_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('lead/new.html.twig', [
            'lead' => $lead,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="lead_show", methods={"GET"})
     */
    public function show(Lead $lead): Response
    {
        return $this->render('lead/show.html.twig', [
            'lead' => $lead,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="lead_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Lead $lead): Response
    {
        $form = $this->createForm(LeadType::class, $lead);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('lead_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('lead/edit.html.twig', [
            'lead' => $lead,
            'form' => $form->createView(),
        ]);
    }
}

templates/lead/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Lead{% endblock %}

{% block body %}
    <h1>Edit Lead</h1>
    {{ form_start(form) }}
        {{ form_widget(form) }}
        <button class="btn btn-primary">{{ button_label|default('Update') }}</button>
    {{ form_end(form) }}

    <a href="{{ path('lead_index') }}">Back to Leads</a>
{% endblock %}

templates/lead/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Leads {% endblock %}

{% block body %}
    <h1>Leads</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Lead Name</th>
                <th>Company Name</th>
                <th>Domain</th>
                <th>Conversion Status</th>
                <th>Broadcast Status</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for lead in leads %}
            <tr>
                <td>{{ lead.id }}</td>
                <td>{{ lead.name }}</td>
                <td>{{ lead.company }}</td>
                <td>{{ lead.domain }}</td>
                <td>{{ lead.conversionStatus ? 'Yes' : 'No' }}</td>
                <td>{{ lead.broadcastStatus ? 'Yes' : 'No' }}</td>
                <td>
                    <a href="{{ path('lead_show', {'id': lead.id}) }}">show</a>
                    <a href="{{ path('lead_edit', {'id': lead.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">No records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/lead/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Lead{% endblock %}

{% block body %}
    <h1>Create new Lead</h1>

   {{ form_start(form) }}
        {{ form_widget(form) }}
        <button class="btn btn-primary">{{ button_label|default('Save') }}</button>
    {{ form_end(form) }}

    <a href="{{ path('lead_index') }}">Back to Leads</a>
{% endblock %}

templates/lead/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Lead{% endblock %}

{% block body %}
    <h1>Lead</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ lead.id }}</td>
            </tr>
            <tr>
                <th>Lead Name</th>
                <td>{{ lead.name }}</td>
            </tr>
            <tr>
                <th>Company Name</th>
                <td>{{ lead.company }}</td>
            </tr>
            <tr>
                <th>Domain</th>
                <td>{{ lead.domain }}</td>
            </tr>
            <tr>
                <th>Conversion Status</th>
                <td>{{ lead.conversionStatus ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Broadcast Status</th>
                <td>{{ lead.broadcastStatus ? 'Yes' : 'No' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('lead_index') }}">Back to Leads</a>

{% endblock %}